// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qqgzldxoirboudlimllz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFxZ3psZHhvaXJib3VkbGltbGx6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3MjQ2MzgsImV4cCI6MjA3MDMwMDYzOH0.ujooyGe3gsHsTs-kGRLwBxiKVmfZ-QKQyJvX1fE0CBY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});